/**
 * THIS FILE IS AUTO-GENERATED.
 *
 * Source: docs/security/openapi.yaml
 * Generator: openapi-typescript (^7.0.0)
 *
 * Re-generate with:
 *   npm run generate:types          (from the repo root)
 *
 * Do not edit this file by hand. Any manual changes will be
 * overwritten the next time generate:types is run.
 */

// Re-run `npm run generate:types` from the repo root to populate this file.
// The command runs: openapi-typescript docs/security/openapi.yaml -o packages/api-types/index.ts

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export type components = Record<string, never>;
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
